w4d3/CatsII/config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :users
  resource :session
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  root to: redirect("/cats")
end

w4d3/CatsII/app/models/user.rb
class User < ActiveRecord::Base

  validates :user_name, :password_digest, presence: true
  #after_initialize :make_session_token

  has_many :cats
  has_many :cat_rental_requests
  has_many(
    :session_tokens,
    class_name: "UserSession"
  )

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    if user && user.is_password?(password)
      return user
    end
    nil
  end

end

w4d3/CatsII/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      login_user!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end

end

w4d3/CatsII/app/views/users/new.html.erb
<h1>Create User</h1>

<form action= "<%= users_url %>" method="POST" >
  <input name="authenticity_token" type = "hidden" value = "<%= form_authenticity_token%>">  
  <label for="user_username">Username</label>
  <input
    id="user_username"
    name="user[user_name]"
    type="text"
    value="<%= @user.user_name %>">
  <label for="user_password">Password</label>
  <input
    id="user_password"
    name="user[password]"
    type="password">

  <input type="submit" value="Create account">
</form>

w4d3/CatsII/app/views/users/show.html.erb
<h1> <%= @user.user_name %> </h1>

<!-- <p>
  <%#= link_to users_url, "User index" %>
</p> -->