w4d5/RedditClone/config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'

  resources :users, only: [:new, :create]

  resource :sessions, only: [:new, :create, :destroy]

  resources :posts, except: [:index, :create]

  resources :subs, except: :destroy do
    resources :posts, only: [:new]
  end

  resources :comments, only: [:show, :destroy, :create]
end

w4d5/RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  has_many :posts
  default_scope { order(title: :asc) }

  belongs_to :moderator, class_name: "User", foreign_key: :moderator_id

  validates :title, :description, :moderator_id, presence: true
  validates :description, length: { maximum: 300 }
  validates :title, uniqueness: true

end

w4d5/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user_id

    if @sub.save
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.nil?
      could_not_find_error
      redirect_to subs_url
    elsif @sub.save
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
  end

  protected

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

w4d5/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

w4d5/RedditClone/app/views/subs/_sub.html.erb
<li>
  <%= link_to sub.title, sub_url(sub) %> <small><%= sub.description %></small>
</li>

w4d5/RedditClone/app/views/subs/_sub_form.html.erb
<% action_url   = ( sub.persisted? ? sub_url(sub) : subs_url ) %>
<% method       = ( sub.persisted? ? "patch" : "post" ) %>
<% button_label = ( sub.persisted? ? "Update" : "Create" ) %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="sub-title">Title</label>
  <input id="sub-title" type="text" name="sub[title]" value="<%= sub.title %>">


  <label for="Description">Description</label>
  <input type="text" name="sub[description]" value="<%= sub.description %>">

  <input type="submit" value="<%= button_label %>">

</form>

w4d5/RedditClone/app/views/subs/index.html.erb
<h1>Subs</h1>

<%= button_to "Create new sub", new_sub_url, method: "get" %>

<ul>
  <%= render @subs %>
</ul>

w4d5/RedditClone/app/views/subs/new.html.erb
<h1>Create a new sub</h1>

<%= render 'sub_form', sub: @sub %>

w4d5/RedditClone/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<small><%= @sub.description %></small>

<%= button_to "New post", new_sub_post_url(@sub) %>

<ul>
  <%= render @posts %>
</ul>